[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npx serve -s build -l 3000"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[environments.production.variables]
NODE_ENV = "production"
PORT = "3000"

