version: '3.8'

services:
  # MongoDB Database for Development
  mongodb-dev:
    image: mongo:7.0
    container_name: soulfriend-mongodb-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: dev123
      MONGO_INITDB_DATABASE: soulfriend_dev
    volumes:
      - mongodb_dev_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"
    networks:
      - soulfriend-dev-network

  # Redis Cache for Development
  redis-dev:
    image: redis:7.2-alpine
    container_name: soulfriend-redis-dev
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass dev123
    volumes:
      - redis_dev_data:/data
    ports:
      - "6379:6379"
    networks:
      - soulfriend-dev-network

  # Backend Development Server
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: soulfriend-backend-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://admin:dev123@mongodb-dev:27017/soulfriend_dev?authSource=admin
      REDIS_URL: redis://:dev123@redis-dev:6379
      JWT_SECRET: dev-jwt-secret-key
      DEFAULT_ADMIN_USERNAME: admin
      DEFAULT_ADMIN_EMAIL: admin@dev.local
      DEFAULT_ADMIN_PASSWORD: Dev123!
    ports:
      - "5000:5000"
    volumes:
      - ./backend/src:/app/src
      - ./backend/package.json:/app/package.json
      - backend_node_modules:/app/node_modules
    depends_on:
      - mongodb-dev
      - redis-dev
    networks:
      - soulfriend-dev-network
    command: npm run dev

  # Frontend Development Server
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: soulfriend-frontend-dev
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
      REACT_APP_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
      - frontend_node_modules:/app/node_modules
    networks:
      - soulfriend-dev-network
    command: npm start

volumes:
  mongodb_dev_data:
    driver: local
  redis_dev_data:
    driver: local
  backend_node_modules:
    driver: local
  frontend_node_modules:
    driver: local

networks:
  soulfriend-dev-network:
    driver: bridge
