database:
  type: psql

services:
  - type: web
    name: soulfriend-api
    env: node
    region: singapore
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
