services:
  # Backend API Service
  - type: web
    name: soulfriend-api
    env: node
    region: singapore
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node simple-gemini-server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: GEMINI_API_KEY
        sync: false
      - key: CORS_ORIGIN
        sync: false
    healthCheckPath: /api/health

