[build]
builder = "nixpacks"
buildCommand = "npm ci --include=dev && npm run build"
nixpacksConfig = { providers = ["nodejs"], variables = { NODE_VERSION = "20" }, phases = { setup = "nix-env -iA nixpkgs.nodejs_20" } }

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[environments.production.variables]
NODE_ENV = "production"
PORT = "5000"
NODE_VERSION = "20"
