[build]
builder = "nixpacks"
buildCommand = "npm run build"
nixpacksConfig = { providers = ["nodejs"] }

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[environments.production.variables]
NODE_ENV = "production"
PORT = "5000"
NODE_VERSION = "20"

