name: Deploy SoulFriend with Learning System

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Render
      run: |
        echo "🚀 Triggering Render deployment..."
        curl -X POST "https://api.render.com/v1/services/srv-8jGdu2vni/deploys" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{"clearCache": "clear"}'
        echo "✅ Backend deployment triggered"

  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Vercel
      run: |
        echo "🚀 Triggering Vercel deployment..."
        curl -X POST "https://api.vercel.com/v13/deployments" \
          -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "name": "frontend",
            "gitSource": {
              "type": "github",
              "repo": "Kendo260599/soulfriend",
              "ref": "main"
            },
            "target": "production"
          }'
        echo "✅ Frontend deployment triggered"

  test-deployment:
    runs-on: ubuntu-latest
    needs: [deploy-backend, deploy-frontend]
    steps:
    - name: Wait for deployment
      run: sleep 300
      
    - name: Test Backend
      run: |
        echo "🧪 Testing backend..."
        curl -f https://soulfriend-api.onrender.com/api/health || exit 1
        curl -f https://soulfriend-api.onrender.com/api/conversation-learning/insights || exit 1
        echo "✅ Backend tests passed"
        
    - name: Test Frontend
      run: |
        echo "🧪 Testing frontend..."
        curl -f https://frontend-8jgdu2vni-kendo260599s-projects.vercel.app || exit 1
        echo "✅ Frontend tests passed"
